name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Generate PDF document
        uses: hspaans/latexmk-action@v1.0.8
        with:
          format: pdf
          filename: homework.tex
          
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.1
        with:
          # Artifact name
          name: Paper
          # A file, directory or wildcard pattern that describes what to upload
          path: homework.pdf
      
